services:
  - type: web
    name: ncufood
    env: python
    plan: free
    region: oregon
    rootDirectory: foodmap/NCUFOODMAP_DJANGO
    buildCommand: pip install -r requirements.txt ; python manage.py collectstatic --noinput ; python manage.py migrate
    startCommand: gunicorn core.wsgi:application --bind=0.0.0.0:$PORT --workers=1 --threads=4 --worker-class=gthread --timeout=120 --graceful-timeout=30 --max-requests=1000 --max-requests-jitter=50 --log-level=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: "17070704622-4fp9a5rdo4v79toifeukpd65jvpv3f4o.apps.googleusercontent.com"
      - key: GOOGLE_OAUTH_SECRET
        value: "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"
      - key: SITE_ID
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "8000"
    healthCheckPath: /healthz
    autoDeploy: true